version: '3.8'

services:
  backend:
    container_name: backend
    build:
      context: ./backend
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - 8000:8000
    environment:
      API_KEY: ${API_KEY}
    restart: unless-stopped
    networks:
      - internal-network
      - default
    depends_on:
      caddy:
        condition: service_started

  caddy:
    container_name: app-proxy
    environment:
      DOMAIN: ${DOMAIN}
    image: caddy:2.6.2-alpine
    ports:
      - '80:80'
      - '443:443'
        #- '8000:8000'
    restart: unless-stopped
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_config: null
  caddy_data: null

networks:
  internal-network:
    name: internal-network
    driver: bridge
