version: '3.8'

services:
  backend:
    container_name: backend
    build:
      context: ./backend
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - 8000:8000
    environment:
      API_KEY: ${API_KEY}
    restart: unless-stopped