// import 'bootstrap/dist/css/bootstrap.css'
import { Inter } from 'next/font/google'
import NavBar from "@/components/NavBar"
// import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'ScanFilApp',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavBar />
        {children}
      </body>
    </html>
  )
}
